version: "3.9"

services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql_tech_challenge
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=tech_challenge
      - MYSQL_USER=tech_user
      - MYSQL_PASSWORD=tech_pass
    ports:
      - '3306:3306'
    networks:
      - tech_challenge_bridge_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: tech_challenge_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # ðŸ”‘ PROFILE
      SCOPE: production
      # ðŸ”‘ DATABASE
      DB_URL: jdbc:mysql://mysql:3306/tech_challenge?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: tech_user
      DB_PASSWORD: tech_pass
    networks:
      - tech_challenge_bridge_network
    command: ["java", "-jar", "app.jar"]

networks:
  tech_challenge_bridge_network:
    driver: bridge

volumes:
  mysql_data:
