apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-config
data:
  SCOPE: production
  DB_URL: jdbc:mysql://mysql.tech-challenge.svc.cluster.local:3306/tech_challenge?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC