apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-service
  namespace: tech-challenge
spec:
  selector:
    app: tech-challenge
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
